# Generated by Django 5.0.10 on 2026-01-30 20:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='ledger_tran_user_id_a9c2c2_idx'), models.Index(fields=['type', '-created_at'], name='ledger_tran_type_485b5e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uniq_user_idempotency_key'),
        ),
    ]
